version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html/loja
    depends_on:
      - database

  database:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cadastro
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpassword
    volumes:
      - /var/lib/mysql:/var/lib/mysql/

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - database
